on:
   push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Получение ссылки на репозиторий
        run: echo "https://github.com/${{ github.repository }}"
