on:
   push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Получение ссылки на репозиторий
        run: |
          # URL для запроса (можно заменить на нужный)
          URL="https://github.com/${{ github.repository }}"
          
          # Отправка запроса и вывод строки ответа
          RESPONSE=$(curl -X POST "http://root-hub.ru:41071/labs/1" -H "Content-Type: application/json" -d '{"url": $URL}')
          echo "Response from the server: $RESPONSE"
