on:
   push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Получение ссылки на репозиторий
        run: |
          # URL для запроса (можно заменить на нужный)
          URL="http://root-hub.ru:41071"
          
          # Отправка запроса и вывод строки ответа
          RESPONSE=$(curl -s $URL)
          echo "Response from the server: $RESPONSE"
