on:
   push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Получение ссылки на репозиторий
        run: |
          RESPONSE=$(curl -X GET "http://root-hub.ru:41071)
          echo "Response from the server: $RESPONSE"
